### PR TITLE
1.13 support

### PR DESCRIPTION
**Pull request by rom1504**
this one won't be as easy as other versions

it will need changes and stuff from https://github.com/PrismarineJS/mineflayer/blob/master/lib/features.json

also see https://github.com/PrismarineJS/flying-squid/issues/341

### CODE REVIEW

**Comment by rom1504** [comment]
in particular https://github.com/PrismarineJS/mineflayer/pull/712/files will probably be useful

**Comment by Deudly** [comment]
Updating Flying-Squid to 1.13

- [x] Server starts
- [ ] diamond-square should be able to generate 1.13 maps and be compatible with < 1.13 versions [PR](https://github.com/PrismarineJS/diamond-square/pull/4)
- [ ] prismarine-chunk update: setBlockData() function for 1.13 [PR](https://github.com/PrismarineJS/prismarine-chunk/pull/90)
- [ ] Block IDs update (place)

Known issues:
- [ ] Only the person who loads the chunk can see the object data. Others (or on reconnect) will see the default block data
- [ ] Breaking a block in survival mode will result in a fatal error

**Comment by rom1504** [comment]
Noticed issues : 
* [ ] no clear error for incorrect saved world version  (not blocking) 
* [ ] drop is broken (go to /gamemode 0 to test)

**Comment by rom1504** [comment]
merging to simplify

follow up at https://github.com/PrismarineJS/flying-squid/issues/416

**Pull request merged**
