### PR TITLE
Use docsify for docs

### PR DESCRIPTION
**Pull request by demipixel**
* Setup support for docsify so it's pretty and organized
* Made "behaviors" separate and improved their docs (until we decide what to do with them)
* Separated classes into their own folders
* Copied some things from current README.md into the docsify README.md. I removed some things like `Features` and `Contributors` from the docsify README so that both READMEs don't have to be changed very often (and also so docsify can mostly focus on plugins/development).

Currently it's placed in /doc/docs which isn't ideal, but I didn't know where else I would put `HISTORY.md` and `CONTRIBUTE.md`.

[Here is a guide](https://docsify.js.org/#/deploy?id=github-pages) on how to display it via github pages (or however else we might want to).

### CODE REVIEW

**Comment by rom1504** [comment]
what is the end result ?

**Comment by demipixel** [comment]
screen shot 2018-05-27 at 10 34 12 am
screen shot 2018-05-27 at 10 34 29 am
screen shot 2018-05-27 at 10 35 12 am
screen shot 2018-05-27 at 10 35 19 am

**Comment by rom1504** [comment]
Oh that's nice indeed.
How do we get that displayed ? gh-pages ?

**Comment by demipixel** [comment]
Yeah, the link to a guide I posted at the top tells you how to install it with github pages, it's pretty fast (I've done it before for one of my own projects).

**Comment by rom1504** [comment]
can you move the files to docs so it can work with github pages ?

**Comment by rom1504** [comment]
* [ ] take new version of history file
* [ ] move full README.md to docs/README.md

**Pull request merged**
