### PR TITLE
JSON localization & etc.

### PR DESCRIPTION
**Pull request by redcarti**
also will be used https://github.com/prismarinejs/prismarine-chat

### CODE REVIEW

**Comment by redcarti** [comment]
oh I'm sorry I can't fix those problems for now and soon. I have converted PR to draft 'cause I didn't fix it. So, yeah.

**Comment by redcarti** [comment]
I have seen some PRs that added JSON translation... I gotta remake it in meantime. Sorry for being too lazy.. uh...

**Comment by u9g** [comment]
this is largely about what my pr in pchat is, its not far from done and would make this a lot easier

**Comment by redcarti** [comment]
I should test it soon. 

my problem is that I'm too lazy and I'm in school. maybe if I wasn't in school I had make it already.

**Comment by rom1504** [comment]
let's try another time

**Pull request closed without merging**
