### PR TITLE
on login set unused slots to null

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by extremeheat** [comment]
Why null (vs undefined)? Could this be done on initialization and not on login?

**Comment by u9g** [comment]
> Why null (vs undefined)? Could this be done on initialization and not on login?

nulls can be checked against and it's the standard in mineflayer, so I adopted it here

**Comment by u9g** [comment]
this change will hopefully only be merged with the /clear one, because that one fixes the tests it breaks

**Comment by extremeheat** [comment]
Okay, then I think this should be done in the createWindow call. Otherwise this should be done after all the other createWindow calls if not already. Else you get a mix of null and undefined.

**Comment by Karang** [comment]
This would be best to to this in the constructor https://github.com/PrismarineJS/prismarine-windows/blob/master/lib/Window.js#L14
```js
this.slots = new Array(slotCount).fill(null)
```

**Comment by u9g** [comment]
remade here: https://github.com/PrismarineJS/prismarine-windows/pull/22

**Pull request closed without merging**
