### PR TITLE
Move to Typescript

### LINKED ISSUE #533: TypeScript Support
What about TypeScript support? Could not find anything about this and could not install any Types. It is a great support in the development and helps to prevent mistakes and better understand what options you have.

### PR DESCRIPTION
**Pull request by MokiyCodes**
## Changes
This PR introduces a few changes:
1. Move to TypeScript (duh) - This also means there are now auto-generated typescript definitions
2. Make test cases use node 14.x and 17.x, rather than just 14.x
3. Use eslint directly; standard complains about typescript's syntax
4. Update Dependencies
5. Add names to each CI/CD step
6. Move linting to a seperate workflow, to avoid unnecesary linting for each node version
7. Add TypeScript `examples/basic.ts`
8. Make `package.json`:`engines.node` be `>=14` instead of the previous `>=8`

In terms of TypeScript types, there's a lot more to be desired, however this is definitely an improvement over vanilla JS.

## Compatability
This, in theory, shouldn't break any dependents, unless they directly import files in the `src` directory.

## Other things of note
[src/lib/plugins/log.ts:49](https://github.com/MokiyCodes/flying-squid/blob/47e9ccde9c9292830518a484ce59433c7ce122cd/src/lib/plugins/log.ts#L49) Removed this weird code that my tsc was complaining about - don't really know why it's there, maybe someone here can re-implement this in a non-broken way.

---

[Conventional Commits](https://conventionalcommits.org) [Fixes #533](https://github.com/PrismarineJS/flying-squid/issues/533)

### CODE REVIEW

**Comment by MokiyCodes** [comment]
The CI runs here won't succeed, considering these don't run `npm run build`

**Comment by MokiyCodes** [comment]
This also fixes #323

**Comment by rom1504** [comment]
can you instead follow the same technical choice we made for the rest of PrismarineJS: adding a .d.ts file and keeping the code in javascript?

**Comment by MokiyCodes** [comment]
> can you instead follow the same technical choice we made for the rest of PrismarineJS: adding a .d.ts file and keeping the code in javascript?

Sure - I'll do that when I have time for that.

**Comment by IceTank** [comment]
> [src/lib/plugins/log.ts:49](https://github.com/MokiyCodes/flying-squid/blob/47e9ccde9c9292830518a484ce59433c7ce122cd/src/lib/plugins/log.ts#L49) Removed this weird code that my tsc was complaining about - don't really know why it's there, maybe someone here can re-implement this in a non-broken way.
This looks like it is patching console.log in a way where it will always put the cursor at a certain position once called. It is probably to make the command line cleaner once stuff has been logged to it. Just like the vanilla minecraft server dose it. No wonder it is throwing linting errors because it overwrites the default console.log. The 'real' way to patch this is to make a new custom logging function and change all console.log to that.

**Comment by Bezouro** [comment]
> can you instead follow the same technical choice we made for the rest of PrismarineJS: adding a .d.ts file and keeping the code in javascript?

@rom1504 
Doesn't this mean more work to maintain the project?
Why go this way when we can have the code already in typescript?

**Pull request closed without merging**
