### PR TITLE
Tab complete & commands

### PR DESCRIPTION
**Pull request by redcarti**
#407. 
Tab complete **done** but needs some more tests.
Commands not ready yet.

### CODE REVIEW

**Comment by rom1504** [comment]
Could you implement tests for tab complete and ban list ?
It should be easy enough to add

**Comment by redcarti** [comment]
why did it mention an issue

**Comment by redcarti** [comment]
№4*

**Comment by redcarti** [comment]
there's the problem:
when I'm waiting msg `bot2 was banned`, it recieves `bot2 quit the game.`
if I will add `bot2 quit the game.` it will broke

**Comment by rom1504** [comment]
You can use an .on and a new Promise instead of an await once

**Comment by rom1504** [comment]
(I should have used the rebased strategy here instead of merge to avoid these useless 15 commits, clicked too fast)

**Pull request merged**
