### PR TITLE
[WIP] Weather Command

### PR DESCRIPTION
**Pull request by OverloadedWolf**
Created the base for the weather command. Currently it will give an
warning if you do not have enough parameters to fulfill the command. It
will, however, crash the server when used properly.

### CODE REVIEW

**Comment by rom1504** [comment]
What is the crash error ?

**Comment by OverloadedWolf** [comment]
let me get the error

**Comment by OverloadedWolf** [comment]
here ya go
http://pastebin.com/WGCqW7yC

**Comment by rom1504** [comment]
Ok, you need to add `const UserError = require('flying-squid').UserError;` at the top of your file.

**Comment by OverloadedWolf** [comment]
ah ok. I will ad that and then create another pull

**Comment by rom1504** [comment]
No, you can add commits in this one.

**Comment by OverloadedWolf** [comment]
ok, so all i need to do is commit and it will be added?

**Comment by rom1504** [comment]
Yeah but actually I merged this one and fixed it in https://github.com/PrismarineJS/flying-squid/commit/e3acaf8555ee5c5094b8553f07d6e55cfbadfd38

thunder and duration are not implemented, if you want to implement them, make another PR ;)

**Comment by OverloadedWolf** [comment]
ok, so you already added the line of code? and I will probably get back to working on this next week after finals are over.

**Comment by rom1504** [comment]
yes

**Pull request merged**
